services:
  ouster_lidar:
    image: ros2_humble_jetson:latest
    platform: linux/arm64/v8
    build:
      context: ..
      dockerfile: docker/DockerfilePreBuild
      target: full
      args:
        - AMENT_WORKSPACE_DIR=${AMENT_WORKSPACE_DIR}
        - USERNAME=${USERNAME:-devuser}
        - USER_UID=${UID:-1000}
        - USER_GID=${UID:-1000}
